export default [
  '',
  'It\'s not a great start to the day lemme tell ya.',
  'Aw man.',
  'Where\'s my two minute guitar solo?',
  'uhhhhhh uhhhhhh.',
  'There\'s a wizard that sits outside Hammersmith Station.',
  'Authority is the real weapon of mass destruction.',
  'You could do some real damage with that badge.',
  'In fact grab whatevr you can I\'ll meet you outside with a van.',
  'Aw, I thought I was being all Sherlock.',
  'Hi I\'m Matt and I typed my Steam 2FA key into the wrong place.',
  'Maybe it works like a reverse card in Uno.',
  'I could tell you, but I\'d have to know the answer first.',
  'Alex "Rat-King" Mendes.',
  'Now I\'m picturing pouring beans all over Alex.',
  'I don\'t have any soap but we\'ve got like 30 bottles of beer here.',
  'I have a suspicion that this is a completely obvious in retrospect side-effect of some work blue had.',
  'So I\'m hoping you broke it and we don\'t have to fix it.',
  'I think the clear solution is to convert the bar area into a Thunderdome.',
  'Tattooed Guy and Smoothskin Guy.',
  'Always good to know that when I\'m hungry I can come to work for a quality roast.',
  'So far my efforts have yielded nothing of value.',
  'Is it possible that something we haven\'t changed is loading in something that has changed.',
  'We found the problem! pub time.',
  'Don\'t leaaaavvve meeeeee.',
  'I see nothing in the console.',
  'Find a friend with a shower.',
  'What did I do to deserve this aggression from you?',
  'If you are alone when you crack open a peanut shell and eat the peanut inside, you are the only person in the world to have ever seen that peanut.',
  'Both concrete and glass are mostly made of sand which makes skyscrapers just really tall sandcastles.',
  'The first person who inhaled helium must have been so relieved when the effects wore off.',
  'Hold on, I got confused while writing the cons.',
  'Good morning all! I\'d like to start off with a joke: Luke Edwards.',
  'Interdasting.',
  'Mm, sounds risky.',
  'No no, java is the most popular language so we have to use that one.',
  'The first time eslint yelled at me about writing things wrong was so confusing.',
  'Marco has absolutely run out of fucks to give here.',
  'Lizard people confirmed.',
  'Don\'t make me burn you out of that hedge.',
  'OH BOY IT\'S A WALL OF TEXT!',
  'The cost of failure is too high.',
  'One day humanity will solve the problem of typing on a computer.',
  'It does not work for me.',
  'Clearly the problem is other people.',
  'Or example, the base of a tree and not a small side table.',
  'Shoulda splashed out on #premium-james.',
  'So instead of making it better, I made it worse!',
  'Also there are lots of bees in here.',
  'I\'m so proud of our coordination.',
  'Hedgevengers, dissassemble!',
  'I feel we should end this conversation.',
  'Can you take paternity leave if your baby is an intangible concept?',
  'Does someone need to describe the 127 forms of srcset somewhere?',
  'To be fair there\'s probably more people in the middle of the atlantic than in antarctica.',
  'My favourite thing about noise cancelling headphones is that I\'m oblivious to the pain I inflict on my laptop.',
  'It has a cool spinny 3D globe too.',
  'How many cats are in them and what state are they in.',
  'I love theoretical boxes.',
  'The build is pining for the fjords.',
  'It looks a bit like a contender for something the Ghost Busters would drive.',
  'Aiming for "highest mouth to body ratio" but best supporting actor would be good too.',
  'I am amp man.',
  'Suhweet.',
  'And if we then find it\'s not our fault we start spamming slam dunk gifs and throw it back in thundercats faces.',
  'There shouldn\'t be a need to assign responsibility like we\'re children.',
  'I dunno but this weird clown guy keeps turning up.',
  'Oh so we\'re just meant to look at our own code and see if it works?',
  '@William for "most damage done with fewest lines of code" award.',
  'I found a bad.',
  'Slowly but surely we defeat communism.',
  'Be the chaos monkey you want to see in the world.',
  'That\'d Brighton his day.',
  'I blame Elementor for most things.',
  'I am both amazed and suspicious.',
  'Smell ya later nerds.',
  'Fingles cringled then.',
  'Hold on to your hats everyone.',
  'The failures go marching two by two, hurrah, hurrah.',
  'It\'s a rollercoaster of emotions today.',
  'If the peanut gallery could get back to work please.',
  'You can\'t see blind people?',
  'Im thuper therial you guyths!',
  'I call it "live-thinking".',
  'Ecapsawhat now?',
  'You\'re off the hook this time Mendes but I\'ll be watching you.',
  'Spinning the wheel of fortune again.',
  'Just so we\'re clear I was maybe 5% of the solution.',
  'AWS is like a wild animal, you have to establish dominance.',
];
